default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

development:
  <<: *default
  database: my_book_space_development

test:
  <<: *default
  database: my_book_space_test

production:
  <<: *default
